version: '3.10'
services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    env_file:
      - app/.env
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    env_file:
      - app/.env
    ports:
      - 5433:5432




